### PR TITLE
[TASK] Add autoload-dev information to manifests

### PR DESCRIPTION
**Pull request by cedricziel**

### CODE REVIEW

**Comment by cedricziel** [comment]
The errors will go away once the same PR on flux is merged.

**Comment by NamelessCoder** [comment]
`autoload-dev` won't be processed for deps even if they're required as `dev-*` (correct me if I'm wrong?). I think we still need to load the dep test classes in the bootstrap?

**Comment by cedricziel** [comment]
Houston we're green! Thanks for lending me your brain :)

**Comment by NamelessCoder** [comment]
Thank you for the spring cleaning :)

**Pull request merged**
