### PR TITLE
[BUGFIX] Fix unchanged inherited properties overriding in sub-pages

### PR DESCRIPTION
**Pull request by romm**
The first param passed to the function `getInheritedPropertyValueByDottedPath()` was a full record array, when it should be a configuration array.

This results in the inherited configuration value always being equal to `null`, and forcing the value to be submitted in each and every sub-page FlexForm. It means that the inheritance was break for every page that was updated.

When changing the value of a configuration value for a root page, all its sub-pages that were saved once were not updated.

This commit fixes this bug by actually sending the configuration to the function.

A nice add-on would be to create an extension upgrade script that processes the entire page tree to fix the corrupted data (proposed by @NamelessCoder). :+1:

### CODE REVIEW

**Comment by romm** [comment]
Please note that I've been testing this fix on configuration for both the current page and its sub-pages. It works well in the two cases.

**Comment by NamelessCoder** [comment]
Looks like the tests are now failing because the method getInheritedConfiguration is not mocked in the subject, or is mocked and has the wrong mocked return value. Hopefully you can adjust that - if not, let me know and I'll try to make time for it soon!

**Comment by romm** [comment]
Indeed, @NamelessCoder thank you for checking what was wrong. :)

Are you ok with the fix?

**Comment by NamelessCoder** [comment]
Perfect - thanks!

**Comment by cedricziel** [comment]
Thank you for your contribution, @romm ! :tada:

**Pull request merged**
