### PR TITLE
[TASK] Introduce memoization in `PageService` for FE environment

### PR DESCRIPTION
**Pull request by romm**
As it has been discussed in #340, pages handled by FluidPages and containing dozens of configuration values currently lead to dozens of massive database queries (like `SELECT * FROM pages WHERE uid='xxx';`), resulting in a huge slow of the application for the first frontend request (next ones are cached, so they are faster).

This commit introduces a memoizer in the `PageService`: if the request is in a frontend environment, it will be used to execute the select-query only once per page-uid.

Please note that the `RecordService` is still used directly in other classes that are used only in backend environment, for instance in: `\FluidTYPO3\Fluidpages\Backend\BackendLayout::postProcessBackendLayout()`.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
@romm could you amend this one and remove the EnvironmentService usage and checks for FE/BE mode? The code you have changed should only be triggered in the FE - good choice btw, or (in the case of loadRecordFromDatabase in Provider) they should be safe to cache at least in Fluidpages' implementation.

**Comment by romm** [comment]
Hi @NamelessCoder are you ok with this?

Concerning the `loadRecordFromDatabase()` function in the `PageProvider`, do you mean it could be cached as well? I took a look at the implementations and couldn't be sure of what could be cached indeed; for instance [FluidTYPO3\Fluidpages\Provider\PageProvider::postProcessRecord()](https://github.com/romm/fluidpages/blob/page-service-memoizer/Classes/Provider/PageProvider.php#L308) may refresh the memoization?

I'll be waiting for your answer. :)

**Comment by romm** [comment]
Seems I'm not lucky with your tests suite, once again it fails and I can't explain why. Can you take a look at this as well?

**Comment by NamelessCoder** [comment]
@romm Could you try this again on dev-development? The situation should be a lot better now.

If you still face performance issues and your templates are sufficiently simple, try setting the `static` Flux form option to `1` which causes the DS to be completely cached - more info at https://github.com/FluidTYPO3/fluidpages/commit/d4ce98a72f3eef6f1cb946ac99917185a5ff82f5

**Comment by romm** [comment]
Hi @NamelessCoder sorry for the late answer, I had no time to deal with this issue until now.

So I did update to [4.1.0](https://github.com/FluidTYPO3/fluidpages/releases/tag/4.1.0), and you're right it did reduce database calls by **a lot**.

I also tested with my own modification (from this PR), and this changes almost nothing, so the PR can be decline IMO (as well as close #340).

Thank you for your work, Claus!

**Comment by NamelessCoder** [comment]
That's good news - thanks for the feedback! :)

**Pull request closed without merging**
