### PR TITLE
[BUGFIX] Error on changing page settings in workspaces

### LINKED ISSUE #321: Error disabling page in workspace
In a workspace, right-clicking a page in the page tree and selecting "disable" leads to a fatal error:

> Catchable fatal error: Argument 2 passed to FluidTYPO3\Flux\Utility\RecursiveArrayUtility::mergeRecursiveOverrule() must be of the type array, null given, called in .../typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php on line 280 and defined in .../typo3conf/ext/flux/Classes/Utility/RecursiveArrayUtility.php on line 77

That problem only occurs for pages which are "fresh" in this workspace. For page records that already exist in this workspace (previous unpublished change), it does not happen:
1. Right click page in workspace, disable -> fatal error
2. Reload page tree
3. Right click page in workspace, disable -> works now

---

This happens with fluidpages git `development` 79bc7b5 on TYPO3 7.6.2:

Seems to be related to #317.

### PR DESCRIPTION
**Pull request by bauermar**
Checking if record and reference are an array. Error will not longer exists (resolves #321)

Closes #321

### CODE REVIEW

**Comment by NamelessCoder** [comment]
On hold until https://github.com/FluidTYPO3/vhs/pull/1134 is taken care of, current version of build utilities make the travis build fail.

Tip: when you create pull requests, start them from a new branch you create off of the development branch. That prevents your own development branch from being flooded with WIP commits ;)

**Comment by NamelessCoder** [comment]
Hi @bauermar - would you mind rebasing this one on the `development` branch so the CI build will succeed? Thanks ;)

**Comment by cedricziel** [comment]
Let's see what happens.

**Comment by NamelessCoder** [comment]
You beat me to it!

**Comment by cedricziel** [comment]
Gently pushing :)

**Comment by NamelessCoder** [comment]
This house... *is clean!*

**Comment by cedricziel** [comment]
It is - thx for the party. ;-)

**Pull request merged**
